---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ coturn_service_name }}'
    consul_services:
      - name: '{{ coturn_service_name }}'
        tags: ['coturn', 'turn', 'stun']
        port: '{{ coturn_listen_port }}'
        address: '{{ ansible_local.wireguard.address }}'
        checks:
          - id:   '{{ coturn_service_name }}-app-health'
            type: 'tcp'
            tcp:  'localhost:{{ coturn_listen_port }}'
