---
- name: Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ coturn_service_name }}'
    consul_services:
      - id:   '{{ coturn_service_name }}'
        name: '{{ coturn_service_name }}'
        tags: ['coturn', 'turn', 'stun']
        port: '{{ coturn_stun_tcp_port }}'
        address: '{{ ansible_local.wireguard.address }}'
        checks:
          - id:   '{{ coturn_service_name }}-app-health'
            type: 'tcp'
            tcp:  'localhost:{{ coturn_stun_tcp_port }}'

      - id:   '{{ coturn_service_name }}-metrics'
        name: '{{ coturn_service_name }}-metrics'
        tags: ['coturn', 'turn', 'stun', 'metrics']
        port: '{{ coturn_metrics_port }}'
        address: '{{ ansible_local.wireguard.address }}'
        checks:
          - id:   '{{ coturn_service_name }}-app-health'
            type: 'http'
            http: 'http://localhost:{{ coturn_metrics_port }}/'
